/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2020-12-22 07:07:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class _04_005fpizza_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/currentTime.jsp", Long.valueOf(1608618958171L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>피자 주문</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\ttable{border: 1px solid black; border-collapse: collapse;}\r\n");
      out.write("\tth,td {border:1px solid black; padding:10px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>오늘은 <span style=\"color: pink;\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Date now = new Date();

	SimpleDateFormat smft 
		= new SimpleDateFormat("yyy-MM-dd HH:mm:ss");
	
	String currentTime = smft.format(now);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<span style=\"color:blue\"> ");
      out.print(currentTime );
      out.write(" </span>");
      out.write("</span> 입니다.\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<h1>피자 아카데미</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>종류</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>가격</th>\r\n");
      out.write("\t\t\t<th rowspan=\"12\"></th>\r\n");
      out.write("\t\t\t<th>종류</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>가격</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"5\">피자</td>\r\n");
      out.write("\t\t\t<td>치즈피자</td>\r\n");
      out.write("\t\t\t<td>5000</td>\r\n");
      out.write("\t\t\t<td rowspan=\"12\">사이드</td>\r\n");
      out.write("\t\t\t<td>오븐구이통닭</td>\r\n");
      out.write("\t\t\t<td>9000</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>콤비네이션피자</td>\r\n");
      out.write("\t\t\t<td>6000</td>\r\n");
      out.write("\t\t\t<td>치킨스틱&윙</td>\r\n");
      out.write("\t\t\t<td>4900</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>포테이토피자</td>\r\n");
      out.write("\t\t\t<td>7000</td>\r\n");
      out.write("\t\t\t<td>치즈오븐스파게티</td>\r\n");
      out.write("\t\t\t<td>4000</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>고구마피자</td>\r\n");
      out.write("\t\t\t<td>7000</td>\r\n");
      out.write("\t\t\t<td>새우링&웨지감자</td>\r\n");
      out.write("\t\t\t<td>3500</td>\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>불고기피자</td>\r\n");
      out.write("\t\t\t<td>8000</td>\r\n");
      out.write("\t\t\t<td>갈릭포테이토</td>\r\n");
      out.write("\t\t\t<td>3000</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"6\">토핑</td>\r\n");
      out.write("\t\t\t<td>고구마무스</td>\r\n");
      out.write("\t\t\t<td>1000</td>\r\n");
      out.write("\t\t\t<td>콜라</td>\r\n");
      out.write("\t\t\t<td>1500</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>콘크림무스</td>\r\n");
      out.write("\t\t\t<td>1500</td>\r\n");
      out.write("\t\t\t<td>사이다</td>\r\n");
      out.write("\t\t\t<td>1500</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>파인애플토핑</td>\r\n");
      out.write("\t\t\t<td>2000</td>\r\n");
      out.write("\t\t\t<td>갈릭소스</td>\r\n");
      out.write("\t\t\t<td>500</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>치즈토핑</td>\r\n");
      out.write("\t\t\t<td>2000</td>\r\n");
      out.write("\t\t\t<td>피클</td>\r\n");
      out.write("\t\t\t<td>300</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>치즈크러스트</td>\r\n");
      out.write("\t\t\t<td>2000</td>\r\n");
      out.write("\t\t\t<td>핫소스</td>\r\n");
      out.write("\t\t\t<td>100</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>치즈바이트</td>\r\n");
      out.write("\t\t\t<td>3000</td>\r\n");
      out.write("\t\t\t<td>파마산 치즈가루</td>\r\n");
      out.write("\t\t\t<td>100</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"/JSPProject/confirmPizza.do\" name=\"myInfoForm\" method=\"post\">\r\n");
      out.write("\t\t피자&nbsp;&nbsp;&nbsp; : \r\n");
      out.write("\t\t<select id=\"pizza\" name=\"pizza\" required>\r\n");
      out.write("\t\t\t<option value=\"치즈피자\">치즈피자</option>\r\n");
      out.write("\t\t\t<option value=\"콤비네이션피자\">콤비네이션피자</option>\r\n");
      out.write("\t\t\t<option value=\"포테이토피자\">포테이토피자</option>\r\n");
      out.write("\t\t\t<option value=\"고구마피자\">고구마피자</option>\r\n");
      out.write("\t\t\t<option value=\"불고기피자\">불고기피자</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t토핑&nbsp;&nbsp;&nbsp; :\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"topping\" id=\"topping1\" value=\"고구마무스\">고구마무스\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"topping\" id=\"topping2\" value=\"콘크림무스\">콘크림무스\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"topping\" id=\"topping3\" value=\"파인애플토핑\">파인애플토핑\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"topping\" id=\"topping4\" value=\"치즈토핑\">치즈토핑\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"topping\" id=\"topping5\" value=\"치즈크러스트\">치즈크러스트\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"topping\" id=\"topping6\" value=\"치즈바이트\">치즈바이트\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t사이드 :\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side1\" value=\"오븐구이통닭\">오븐구이통닭\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side2\" value=\"치킨스틱&윙\">치킨스틱&윙\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side3\" value=\"치즈오븐스파게티\">치즈오븐스파게티\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side4\" value=\"새우링&웨지감자\">새우링&웨지감자\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side5\" value=\"갈릭포테이토\">갈릭포테이토\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side6\" value=\"콜라\">콜라\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side7\" value=\"사이다\">사이다\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side8\" value=\"갈릭소스\">갈릭소스\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side9\" value=\"피클\">피클\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side10\" value=\"핫소스\">핫소스\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"side\" id=\"side11\" value=\"파마산 치즈가루\">파마산 치즈가루\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<button type=\"submit\">주문하기</button>\r\n");
      out.write("\t</form>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
